import { PrismaClient } from '@prisma/client';
import { Server as SocketIOServer } from 'socket.io';
import QRCode from 'qrcode';
import pino from 'pino';
import path from 'path';
import fs from 'fs';

export class WhatsAppService {
  private io: SocketIOServer | null = null;
  private prisma: PrismaClient;
  private qrCode: string | null = null;
  private status: 'disconnected' | 'qr_ready' | 'connecting' | 'connected' = 'qr_ready';
  private sock: any = null;
  private accountPhone: string | null = null;
  private authDir: string;

  constructor(prisma: PrismaClient) {
    this.prisma = prisma;
    this.authDir = path.join(process.cwd(), 'whatsapp_auth_session');
    if (!fs.existsSync(this.authDir)) {
      fs.mkdirSync(this.authDir, { recursive: true });
    }
  }

  public setSocketIO(io: SocketIOServer) {
    this.io = io;
  }

  public async initialize() {
    this.startBaileysSocket().catch((e) => {
      console.warn('Baileys initial connect fallback:', e);
    });
  }

  public async startBaileysSocket() {
    try {
      // Dynamic import of Baileys Multi-Device engine
      const baileys = await import('@whiskeysockets/baileys');
      const makeWASocket = baileys.default || baileys.makeWASocket;
      const { useMultiFileAuthState, DisconnectReason } = baileys;

      const { state, saveCreds } = await useMultiFileAuthState(this.authDir);

      this.status = 'connecting';
      this.broadcastStatus();

      this.sock = makeWASocket({
        auth: state,
        printQRInTerminal: false,
        logger: pino({ level: 'silent' }),
        browser: ['Recruiting CRM', 'Chrome', '1.0.0']
      });

      this.sock.ev.on('creds.update', saveCreds);

      this.sock.ev.on('connection.update', async (update: any) => {
        const { connection, lastDisconnect, qr } = update;

        if (qr) {
          // Real WhatsApp Web QR string generated by Meta
          this.qrCode = await QRCode.toDataURL(qr, {
            errorCorrectionLevel: 'M',
            margin: 2,
            scale: 8
          });
          this.status = 'qr_ready';
          this.broadcastStatus();
          await this.persistSession();
        }

        if (connection === 'close') {
          const shouldReconnect = (lastDisconnect?.error as any)?.output?.statusCode !== DisconnectReason.loggedOut;
          this.status = 'disconnected';
          this.broadcastStatus();
          if (shouldReconnect) {
            setTimeout(() => this.startBaileysSocket(), 5000);
          }
        } else if (connection === 'open') {
          this.status = 'connected';
          this.qrCode = null;
          const userJid = this.sock?.user?.id || '';
          this.accountPhone = userJid.split(':')[0] || userJid.split('@')[0] || '+380734277174';
          this.broadcastStatus();
          await this.persistSession('Корпоративний WhatsApp', `+${this.accountPhone.replace(/\D/g, '')}`);
        }
      });

      // Handle real incoming messages from WhatsApp candidates and clients
      this.sock.ev.on('messages.upsert', async (m: any) => {
        if (m.type === 'notify') {
          for (const msg of m.messages) {
            if (!msg.key.fromMe && msg.message) {
              const fromJid = msg.key.remoteJid || '';
              const text = msg.message.conversation || msg.message.extendedTextMessage?.text || '[Медіа / Документ]';
              const pushName = msg.pushName || fromJid.split('@')[0];
              const phone = fromJid.split('@')[0];

              await this.handleIncomingMessage(phone, pushName, text);
            }
          }
        }
      });
    } catch (err) {
      console.warn('Baileys running in resilient mode:', err);
    }
  }

  public async getStatus() {
    return {
      channel: 'whatsapp',
      status: this.status,
      qrCodeData: this.qrCode,
      phone: this.accountPhone || '+380 (73) 427-71-74',
      accountName: 'Корпоративний WhatsApp Business',
      updatedAt: new Date()
    };
  }

  public async generateQR() {
    if (!this.sock) {
      await this.startBaileysSocket();
    }
    return this.qrCode;
  }

  public async disconnect() {
    try {
      if (this.sock) {
        await this.sock.logout();
      }
    } catch (e) {}
    this.status = 'disconnected';
    this.qrCode = null;
    this.accountPhone = null;
    if (fs.existsSync(this.authDir)) {
      fs.rmSync(this.authDir, { recursive: true, force: true });
    }
    this.broadcastStatus();
    await this.persistSession();
    setTimeout(() => this.startBaileysSocket(), 2000);
  }

  public async sendMessage(toPhone: string, text: string, dealId?: string, contactId?: string) {
    const cleanPhone = toPhone.replace(/\D/g, '');

    // Send via real WhatsApp WebSocket if active
    if (this.sock && this.status === 'connected') {
      try {
        const jid = `${cleanPhone}@s.whatsapp.net`;
        await this.sock.sendMessage(jid, { text });
      } catch (err) {
        console.warn('Error sending via real Baileys socket:', err);
      }
    }

    const savedMsg = await this.prisma.chatMessage.create({
      data: {
        channel: 'whatsapp',
        direction: 'outgoing',
        dealId,
        contactId,
        senderPhone: cleanPhone,
        text,
        status: 'sent'
      }
    });

    if (this.io) {
      this.io.emit('new_message', savedMsg);
    }

    return savedMsg;
  }

  public async handleIncomingMessage(phone: string, pushName: string, text: string) {
    try {
      const cleanPhone = phone.replace(/\D/g, '');

      // 1. Find or create Contact
      let contact = await this.prisma.contact.findFirst({
        where: {
          OR: [
            { whatsapp: { contains: cleanPhone } },
            { phone: { contains: cleanPhone } }
          ]
        }
      });

      if (!contact) {
        contact = await this.prisma.contact.create({
          data: {
            name: pushName || `Клієнт WhatsApp (${cleanPhone})`,
            phone: `+${cleanPhone}`,
            whatsapp: `+${cleanPhone}`,
            type: 'employer'
          }
        });
      }

      // 2. Find active Deal
      let deal = await this.prisma.deal.findFirst({
        where: { contactId: contact.id },
        orderBy: { updatedAt: 'desc' }
      });

      if (!deal) {
        const defaultPipeline = await this.prisma.pipeline.findFirst({
          where: { isDefault: true },
          include: { stages: { orderBy: { sortOrder: 'asc' } } }
        });

        const firstStage = defaultPipeline?.stages[0];
        const adminUser = await this.prisma.user.findFirst();

        if (defaultPipeline && firstStage && adminUser) {
          deal = await this.prisma.deal.create({
            data: {
              title: `Запит WhatsApp: ${contact.name}`,
              budget: 0,
              pipelineId: defaultPipeline.id,
              stageId: firstStage.id,
              responsibleId: adminUser.id,
              contactId: contact.id,
              tags: JSON.stringify(['WhatsApp', 'Вхідний']),
              projectId: 'employers'
            }
          });

          if (this.io) {
            this.io.emit('deal_created', deal);
          }
        }
      }

      // 3. Save message
      const savedMsg = await this.prisma.chatMessage.create({
        data: {
          channel: 'whatsapp',
          direction: 'incoming',
          dealId: deal?.id,
          contactId: contact.id,
          senderName: pushName,
          senderPhone: cleanPhone,
          text,
          status: 'sent'
        }
      });

      if (this.io) {
        this.io.emit('new_message', savedMsg);
        this.io.emit('notification', {
          title: `Нове повідомлення WhatsApp від ${pushName}`,
          body: text,
          dealId: deal?.id
        });
      }

      return savedMsg;
    } catch (err) {
      console.error('Error handling incoming WhatsApp message:', err);
    }
  }

  private broadcastStatus() {
    if (this.io) {
      this.io.emit('messenger_status', {
        channel: 'whatsapp',
        status: this.status,
        qrCodeData: this.qrCode,
        phone: this.accountPhone
      });
    }
  }

  private async persistSession(accountName?: string, phone?: string) {
    try {
      await this.prisma.messengerSession.upsert({
        where: { channel: 'whatsapp' },
        create: {
          channel: 'whatsapp',
          status: this.status,
          qrCodeData: this.qrCode,
          accountName: accountName || 'WhatsApp Бізнес',
          phone: phone || null
        },
        update: {
          status: this.status,
          qrCodeData: this.qrCode,
          accountName: accountName !== undefined ? accountName : undefined,
          phone: phone !== undefined ? phone : undefined
        }
      });
    } catch (e) {}
  }
}
